### ISSUE TITLE
Move eo-editor and phi-editor to this repo

### ISSUE THREAD

**Issue by yegor256** [objectionary/try-phi#28]
Would be great if we can move [EO editor](https://github.com/br4ch1st0chr0n3/eo-editor) and [Phi editor](https://github.com/br4ch1st0chr0n3/phi-editor) to this repo.

**Comment by yegor256** [comment]
@br4ch1st0chr0n3 can you please help?

**Comment by br4ch1st0chr0n3** [comment]
Sure, they're here in the `editors` dir

**Comment by br4ch1st0chr0n3** [comment]
However, their GH Pages remain in my repos
